# http port set
server:
  port: 8585

# Oracle Connect
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: angbit
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver


# ORM JPA
  jpa:
    hibernate:
      ddl-auto : none
     
    
# gmail Transfer, smtp(샌드 메일 트랜스퍼 프로토콜)
  mail:
    host: smtp.gmail.com
    port: 587
    username: angbit456@gmail.com
    password: a123456789@
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true    
      
# DEVTOOLS
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      
# Mybatis
mybatis:
  # dto Location
  type-aliases-package: com.oracle.Angbit.model   
  # XML Location
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml