# http port set
server:
  port: 8585

# Oracle Connect
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: angbit
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver



# ORM JPA
  jpa:  
    hibernate:
      ddl-auto : none
      
# DEVTOOLS
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      
# Mybatis
mybatis:
  # dto Location
  type-aliases-package: com.oracle.Angbit.model   
  # XML Location
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml